//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.IService
{
    using System;
    using System.Collections.Generic;
    
    public partial interface IRolePerRelationship:IBaseService<MODEL.RolePerRelationship>
    {
    
    }
}
