//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.Respository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department:BaseRespository<MODEL.Department>,CRM11.IRespository.IDepartment
    {
    
    }
}
