//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.Respository
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowApplyDetail:BaseRespository<MODEL.WorkFlowApplyDetail>,CRM11.IRespository.IWorkFlowApplyDetail
    {
    
    }
}
