//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.Respository
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowNodeRole:BaseRespository<MODEL.WorkFlowNodeRole>,CRM11.IRespository.IWorkFlowNodeRole
    {
    
    }
}
