//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.Respository
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFLow:BaseRespository<MODEL.WorkFLow>,CRM11.IRespository.IWorkFLow
    {
    
    }
}
