//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.IRespository
{
    using System;
    using System.Collections.Generic;
    
    public partial interface IEmployee:IBaseRespository<MODEL.Employee>
    {
    
    }
}
