//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.MODEL
{
	public partial class RolePerRelationship
	{
		public RolePerRelationship ToPOCO(){
			return new RolePerRelationship(){
								rprId=this.rprId,
				rprRoleId=this.rprRoleId,
				rprPerId=this.rprPerId,
			};
		}
	}
}
