//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.MODEL
{
	public partial class WorkFlowNode
	{
		public WorkFlowNode ToPOCO(){
			return new WorkFlowNode(){
								wfnId=this.wfnId,
				wfnWFId=this.wfnWFId,
				wfnName=this.wfnName,
				wfnPrevNodeId=this.wfnPrevNodeId,
				wfnNextNodeId=this.wfnNextNodeId,
				wfnType=this.wfnType,
				wfnBLLClassName=this.wfnBLLClassName,
				wfnOrder=this.wfnOrder,
				wfnIsDel=this.wfnIsDel,
				wfnAddtime=this.wfnAddtime,
			};
		}
	}
}
