//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.MODEL
{
	public partial class WorkFLow
	{
		public WorkFLow ToPOCO(){
			return new WorkFLow(){
								wfId=this.wfId,
				wfName=this.wfName,
				wfHtmlSrc=this.wfHtmlSrc,
				wfIsDel=this.wfIsDel,
				wfAddtime=this.wfAddtime,
			};
		}
	}
}
