//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.MODEL
{
	public partial class WorkFlowApply
	{
		public WorkFlowApply ToPOCO(){
			return new WorkFlowApply(){
								wfaId=this.wfaId,
				wfaWFId=this.wfaWFId,
				wfaCurNodeId=this.wfaCurNodeId,
				wfaUserId=this.wfaUserId,
				wfaTitle=this.wfaTitle,
				wfaContent=this.wfaContent,
				wfaRemark=this.wfaRemark,
				wfaPriority=this.wfaPriority,
				wfaStatue=this.wfaStatue,
				wfaAddTime=this.wfaAddTime,
				wfaIsDel=this.wfaIsDel,
			};
		}
	}
}
