
 //------------------------------------------------------------------------------
// <auto-generated>
// 数据仓储接口，作用：
// 1.调用EF容器 批量 执行 sql语句
// 2.方便通过 子接口属性直接 获取 对应数据表的操作接口对象
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.Respository
{
    using System;
    public partial class DBSession:CRM11.IRespository.IDBSession
    {
    	CRM11.IRespository.IDepartment _Department;
        public CRM11.IRespository.IDepartment Department 
        { 
        	get
        	{
                if (_Department == null)
                    _Department = new Department();
                return _Department;
        	}
        }
    
    	CRM11.IRespository.IEmployee _Employee;
        public CRM11.IRespository.IEmployee Employee 
        { 
        	get
        	{
                if (_Employee == null)
                    _Employee = new Employee();
                return _Employee;
        	}
        }
    
    	CRM11.IRespository.IEmpRoleRelation _EmpRoleRelation;
        public CRM11.IRespository.IEmpRoleRelation EmpRoleRelation 
        { 
        	get
        	{
                if (_EmpRoleRelation == null)
                    _EmpRoleRelation = new EmpRoleRelation();
                return _EmpRoleRelation;
        	}
        }
    
    	CRM11.IRespository.IPermission _Permission;
        public CRM11.IRespository.IPermission Permission 
        { 
        	get
        	{
                if (_Permission == null)
                    _Permission = new Permission();
                return _Permission;
        	}
        }
    
    	CRM11.IRespository.IRole _Role;
        public CRM11.IRespository.IRole Role 
        { 
        	get
        	{
                if (_Role == null)
                    _Role = new Role();
                return _Role;
        	}
        }
    
    	CRM11.IRespository.IRolePerRelationship _RolePerRelationship;
        public CRM11.IRespository.IRolePerRelationship RolePerRelationship 
        { 
        	get
        	{
                if (_RolePerRelationship == null)
                    _RolePerRelationship = new RolePerRelationship();
                return _RolePerRelationship;
        	}
        }
    
    	CRM11.IRespository.IVipPermssion _VipPermssion;
        public CRM11.IRespository.IVipPermssion VipPermssion 
        { 
        	get
        	{
                if (_VipPermssion == null)
                    _VipPermssion = new VipPermssion();
                return _VipPermssion;
        	}
        }
    
    	CRM11.IRespository.IWorkFLow _WorkFLow;
        public CRM11.IRespository.IWorkFLow WorkFLow 
        { 
        	get
        	{
                if (_WorkFLow == null)
                    _WorkFLow = new WorkFLow();
                return _WorkFLow;
        	}
        }
    
    	CRM11.IRespository.IWorkFlowApply _WorkFlowApply;
        public CRM11.IRespository.IWorkFlowApply WorkFlowApply 
        { 
        	get
        	{
                if (_WorkFlowApply == null)
                    _WorkFlowApply = new WorkFlowApply();
                return _WorkFlowApply;
        	}
        }
    
    	CRM11.IRespository.IWorkFlowApplyDetail _WorkFlowApplyDetail;
        public CRM11.IRespository.IWorkFlowApplyDetail WorkFlowApplyDetail 
        { 
        	get
        	{
                if (_WorkFlowApplyDetail == null)
                    _WorkFlowApplyDetail = new WorkFlowApplyDetail();
                return _WorkFlowApplyDetail;
        	}
        }
    
    	CRM11.IRespository.IWorkFlowNode _WorkFlowNode;
        public CRM11.IRespository.IWorkFlowNode WorkFlowNode 
        { 
        	get
        	{
                if (_WorkFlowNode == null)
                    _WorkFlowNode = new WorkFlowNode();
                return _WorkFlowNode;
        	}
        }
    
    	CRM11.IRespository.IWorkFlowNodeRole _WorkFlowNodeRole;
        public CRM11.IRespository.IWorkFlowNodeRole WorkFlowNodeRole 
        { 
        	get
        	{
                if (_WorkFlowNodeRole == null)
                    _WorkFlowNodeRole = new WorkFlowNodeRole();
                return _WorkFlowNodeRole;
        	}
        }
    
    	CRM11.IRespository.IWorkFlowBLLBranchNode _WorkFlowBLLBranchNode;
        public CRM11.IRespository.IWorkFlowBLLBranchNode WorkFlowBLLBranchNode 
        { 
        	get
        	{
                if (_WorkFlowBLLBranchNode == null)
                    _WorkFlowBLLBranchNode = new WorkFlowBLLBranchNode();
                return _WorkFlowBLLBranchNode;
        	}
        }
    
    }
}
