//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Employee = new HashSet<Employee>();
            this.Role = new HashSet<Role>();
        }
    
        public int depId { get; set; }
        public string depName { get; set; }
        public string depRemark { get; set; }
        public bool depIsDel { get; set; }
        public System.DateTime depAddTime { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<Role> Role { get; set; }
    }
}
