//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmpRoleRelation = new HashSet<EmpRoleRelation>();
            this.VipPermssion = new HashSet<VipPermssion>();
            this.WorkFlowApply = new HashSet<WorkFlowApply>();
            this.WorkFlowApplyDetail = new HashSet<WorkFlowApplyDetail>();
        }
    
        public int empId { get; set; }
        public Nullable<int> empDepId { get; set; }
        public string empCnName { get; set; }
        public string empLoginName { get; set; }
        public string empLoginPwd { get; set; }
        public bool empSex { get; set; }
        public short empAge { get; set; }
        public string empCellPhone { get; set; }
        public string empPhone { get; set; }
        public string empAddress { get; set; }
        public bool empIsDel { get; set; }
        public System.DateTime empAddTime { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<EmpRoleRelation> EmpRoleRelation { get; set; }
        public virtual ICollection<VipPermssion> VipPermssion { get; set; }
        public virtual ICollection<WorkFlowApply> WorkFlowApply { get; set; }
        public virtual ICollection<WorkFlowApplyDetail> WorkFlowApplyDetail { get; set; }
    }
}
