//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.RolePerRelationship = new HashSet<RolePerRelationship>();
            this.VipPermssion = new HashSet<VipPermssion>();
        }
    
        public int perId { get; set; }
        public int perParent { get; set; }
        public string perName { get; set; }
        public string perRemark { get; set; }
        public string perAreaName { get; set; }
        public string perControllerName { get; set; }
        public string perActionName { get; set; }
        public short perFormMethod { get; set; }
        public short perOperationType { get; set; }
        public string perJsMethodName { get; set; }
        public string perIco { get; set; }
        public bool perIsLink { get; set; }
        public int perOrder { get; set; }
        public bool perIsShow { get; set; }
        public bool perIsDel { get; set; }
        public System.DateTime perAddTime { get; set; }
    
        public virtual ICollection<RolePerRelationship> RolePerRelationship { get; set; }
        public virtual ICollection<VipPermssion> VipPermssion { get; set; }
    }
}
