//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFLow
    {
        public WorkFLow()
        {
            this.WorkFlowApply = new HashSet<WorkFlowApply>();
            this.WorkFlowNode = new HashSet<WorkFlowNode>();
        }
    
        public int wfId { get; set; }
        public string wfName { get; set; }
        public string wfHtmlSrc { get; set; }
        public bool wfIsDel { get; set; }
        public System.DateTime wfAddtime { get; set; }
    
        public virtual ICollection<WorkFlowApply> WorkFlowApply { get; set; }
        public virtual ICollection<WorkFlowNode> WorkFlowNode { get; set; }
    }
}
