//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowApplyDetail
    {
        public int wfadId { get; set; }
        public int wfadApplyId { get; set; }
        public int wfadCurNodeId { get; set; }
        public int wfadUserId { get; set; }
        public string wfadContent { get; set; }
        public short wfadOperation { get; set; }
        public System.DateTime wfadAddTime { get; set; }
        public bool wfadIsDel { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual WorkFlowApply WorkFlowApply { get; set; }
        public virtual WorkFlowNode WorkFlowNode { get; set; }
    }
}
