//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowNode
    {
        public WorkFlowNode()
        {
            this.WorkFlowApply = new HashSet<WorkFlowApply>();
            this.WorkFlowApplyDetail = new HashSet<WorkFlowApplyDetail>();
            this.WorkFlowBLLBranchNode = new HashSet<WorkFlowBLLBranchNode>();
            this.WorkFlowBLLBranchNode1 = new HashSet<WorkFlowBLLBranchNode>();
            this.WorkFlowNodeRole = new HashSet<WorkFlowNodeRole>();
        }
    
        public int wfnId { get; set; }
        public int wfnWFId { get; set; }
        public string wfnName { get; set; }
        public int wfnPrevNodeId { get; set; }
        public int wfnNextNodeId { get; set; }
        public short wfnType { get; set; }
        public string wfnBLLClassName { get; set; }
        public int wfnOrder { get; set; }
        public bool wfnIsDel { get; set; }
        public System.DateTime wfnAddtime { get; set; }
    
        public virtual WorkFLow WorkFLow { get; set; }
        public virtual ICollection<WorkFlowApply> WorkFlowApply { get; set; }
        public virtual ICollection<WorkFlowApplyDetail> WorkFlowApplyDetail { get; set; }
        public virtual ICollection<WorkFlowBLLBranchNode> WorkFlowBLLBranchNode { get; set; }
        public virtual ICollection<WorkFlowBLLBranchNode> WorkFlowBLLBranchNode1 { get; set; }
        public virtual ICollection<WorkFlowNodeRole> WorkFlowNodeRole { get; set; }
    }
}
