
 //------------------------------------------------------------------------------
// <auto-generated>
// 业务仓储接口，作用：
// 1.调用数据仓储 SaveChanges 批量 执行 sql语句
// 2.方便通过 子接口属性直接 获取 对应业务子接口对象
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.IService
{
    using System;
    public partial interface IServiceSession
    {
        CRM11.IService.IDepartment Department 
    	{ 
    		get;
    	}
    
        CRM11.IService.IEmployee Employee 
    	{ 
    		get;
    	}
    
        CRM11.IService.IEmpRoleRelation EmpRoleRelation 
    	{ 
    		get;
    	}
    
        CRM11.IService.IPermission Permission 
    	{ 
    		get;
    	}
    
        CRM11.IService.IRole Role 
    	{ 
    		get;
    	}
    
        CRM11.IService.IRolePerRelationship RolePerRelationship 
    	{ 
    		get;
    	}
    
        CRM11.IService.IVipPermssion VipPermssion 
    	{ 
    		get;
    	}
    
        CRM11.IService.IWorkFLow WorkFLow 
    	{ 
    		get;
    	}
    
        CRM11.IService.IWorkFlowApply WorkFlowApply 
    	{ 
    		get;
    	}
    
        CRM11.IService.IWorkFlowApplyDetail WorkFlowApplyDetail 
    	{ 
    		get;
    	}
    
        CRM11.IService.IWorkFlowNode WorkFlowNode 
    	{ 
    		get;
    	}
    
        CRM11.IService.IWorkFlowNodeRole WorkFlowNodeRole 
    	{ 
    		get;
    	}
    
        CRM11.IService.IWorkFlowBLLBranchNode WorkFlowBLLBranchNode 
    	{ 
    		get;
    	}
    
    }
}
